# Generated by Django 3.1.5 on 2021-01-23 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0002_auto_20210123_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expens',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expens', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la dépense'),
        ),
    ]
