# Generated by Django 3.1.5 on 2021-02-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20210124_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expens',
            name='comment',
            field=models.TextField(blank=True, max_length=512, verbose_name='Commentaires'),
        ),
    ]
