# Generated by Django 3.1.5 on 2021-02-12 21:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0006_auto_20210210_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Salaire')),
                ('ddate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, max_length=512, verbose_name='Commentaires')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salary', to=settings.AUTH_USER_MODEL, verbose_name='Personne qui a eu ce salaire')),
            ],
            options={
                'verbose_name_plural': 'Salaries',
                'ordering': ['amount'],
            },
        ),
    ]
